name: Build and Test

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-test:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install CMake
      uses: lukka/get-cmake@latest
    
    - name: Configure CMake
      run: |
        New-Item -Path build -ItemType Directory -Force
        cd build
        cmake -DCMAKE_BUILD_TYPE=Debug ..
      shell: pwsh
    
    - name: Build
      run: |
        cd build
        cmake --build . --config Debug
      shell: pwsh
    
    - name: Check Build Output
      run: |
        Get-ChildItem -Path build/bin/Debug -Force
        if (-not (Test-Path "build/bin/Debug/semi_vibe_device.dll")) {
          Write-Error "Device DLL not found!"
          exit 1
        }
        if (-not (Test-Path "build/bin/Debug/semi_vibe_driver.dll")) {
          Write-Error "Driver DLL not found!"
          exit 1
        }
      shell: pwsh
    
    - name: Run Tests
      run: |
        python run_tests.py
      shell: pwsh
    
    - name: Create Artifact Directory
      run: |
        New-Item -Path artifacts/include -ItemType Directory -Force
        New-Item -Path artifacts/lib -ItemType Directory -Force
        New-Item -Path artifacts/bin -ItemType Directory -Force
      shell: pwsh
    
    - name: Copy Headers and DLLs to Artifact Directory
      run: |
        # Copy header files
        Copy-Item -Path include/*.h -Destination artifacts/include/
        
        # Copy DLLs
        Copy-Item -Path build/bin/Debug/*.dll -Destination artifacts/bin/
        
        # Copy lib files if they exist
        if (Test-Path "build/lib/Debug/*.lib") {
          Copy-Item -Path build/lib/Debug/*.lib -Destination artifacts/lib/
        } else {
          Write-Host "No lib files found"
        }
      shell: pwsh
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: semi-vibe-driver-package
        path: artifacts/
        retention-days: 7

  # This job is just for the build status badge
  build-status:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build succeeded"

  # This job is just for the test status badge
  test-status:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - run: echo "Tests passed" 